{{- if not .Values.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oncall.fullname" . }}-schedule
  labels: {{- include "oncall.labels" . | nindent 4 }}
data:
  schedule.yaml: |
{{ .Values.schedule | indent 4 }}
  {{- if .Values.holidays }}
  holidays.yaml: |
{{ .Values.holidays | indent 4 }}
  {{- end }}
{{- end }}
