{{- if .Values.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oncall.fullname" . }}-token
  labels: {{- include "oncall.labels" . | nindent 4 }}
type: Opaque
stringData:
  ONCALL_TOKEN: {{ .Values.token | quote }}
{{- end }}
